apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: obvious-hookworm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: obvious-hookworm-nodejs 
  name: obvious-hookworm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: obvious-hookworm-nodejs 
